public enum Currency
{
    AED = 1,   // UAE Dirham
    AFN = 2,   // Afghan Afghani
    ALL = 3,   // Albanian Lek
    AMD = 4,   // Armenian Dram
    ANG = 5,   // Netherlands Antillean Guilder
    AOA = 6,   // Angolan Kwanza
    ARS = 7,   // Argentine Peso
    AUD = 8,   // Australian Dollar
    AWG = 9,   // Aruban Florin
    AZN = 10,  // Azerbaijani Manat
    BAM = 11,  // Bosnia-Herzegovina Convertible Mark
    BBD = 12,  // Barbadian Dollar
    BDT = 13,  // Bangladeshi Taka
    BGN = 14,  // Bulgarian Lev
    BHD = 15,  // Bahraini Dinar
    BIF = 16,  // Burundian Franc
    BMD = 17,  // Bermudian Dollar
    BND = 18,  // Brunei Dollar
    BOB = 19,  // Bolivian Boliviano
    BRL = 20,  // Brazilian Real
    BSD = 21,  // Bahamian Dollar
    BTN = 22,  // Bhutanese Ngultrum
    BWP = 23,  // Botswanan Pula
    BYN = 24,  // Belarusian Ruble
    BZD = 25,  // Belize Dollar
    CAD = 26,  // Canadian Dollar
    CDF = 27,  // Congolese Franc
    CHF = 28,  // Swiss Franc
    CLP = 29,  // Chilean Peso
    CNY = 30,  // Chinese Yuan
    COP = 31,  // Colombian Peso
    CRC = 32,  // Costa Rican Colón
    CUP = 33,  // Cuban Peso
    CVE = 34,  // Cape Verdean Escudo
    CZK = 35,  // Czech Koruna
    DJF = 36,  // Djiboutian Franc
    DKK = 37,  // Danish Krone
    DOP = 38,  // Dominican Peso
    DZD = 39,  // Algerian Dinar
    EGP = 40,  // Egyptian Pound
    ERN = 41,  // Eritrean Nakfa
    ETB = 42,  // Ethiopian Birr
    EUR = 43,  // Euro
    FJD = 44,  // Fijian Dollar
    FKP = 45,  // Falkland Islands Pound
    FOK = 46,  // Faroese Króna
    GBP = 47,  // British Pound
    GEL = 48,  // Georgian Lari
    GGP = 49,  // Guernsey Pound
    GHS = 50,  // Ghanaian Cedi
    GIP = 51,  // Gibraltar Pound
    GMD = 52,  // Gambian Dalasi
    GNF = 53,  // Guinean Franc
    GTQ = 54,  // Guatemalan Quetzal
    GYD = 55,  // Guyanaese Dollar
    HKD = 56,  // Hong Kong Dollar
    HNL = 57,  // Honduran Lempira
    HRK = 58,  // Croatian Kuna
    HTG = 59,  // Haitian Gourde
    HUF = 60,  // Hungarian Forint
    IDR = 61,  // Indonesian Rupiah
    ILS = 62,  // Israeli New Shekel
    IMP = 63,  // Isle of Man Pound
    INR = 64,  // Indian Rupee
    IQD = 65,  // Iraqi Dinar
    IRR = 66,  // Iranian Rial
    ISK = 67,  // Icelandic Króna
    JEP = 68,  // Jersey Pound
    JMD = 69,  // Jamaican Dollar
    JOD = 70,  // Jordanian Dinar
    JPY = 71,  // Japanese Yen
    KES = 72,  // Kenyan Shilling
    KGS = 73,  // Kyrgyzstani Som
    KHR = 74,  // Cambodian Riel
    KID = 75,  // Kiribati Dollar
    KMF = 76,  // Comorian Franc
    KRW = 77,  // South Korean Won
    KWD = 78,  // Kuwaiti Dinar
    KYD = 79,  // Cayman Islands Dollar
    KZT = 80,  // Kazakhstani Tenge
    LAK = 81,  // Lao Kip
    LBP = 82,  // Lebanese Pound
    LKR = 83,  // Sri Lankan Rupee
    LRD = 84,  // Liberian Dollar
    LSL = 85,  // Lesotho Loti
    LYD = 86,  // Libyan Dinar
    MAD = 87,  // Moroccan Dirham
    MDL = 88,  // Moldovan Leu
    MGA = 89,  // Malagasy Ariary
    MKD = 90,  // Macedonian Denar
    MMK = 91,  // Myanmar Kyat
    MNT = 92,  // Mongolian Tögrög
    MOP = 93,  // Macanese Pataca
    MRU = 94,  // Mauritanian Ouguiya
    MUR = 95,  // Mauritian Rupee
    MVR = 96,  // Maldivian Rufiyaa
    MWK = 97,  // Malawian Kwacha
    MXN = 98,  // Mexican Peso
    MYR = 99,  // Malaysian Ringgit
    MZN = 100, // Mozambican Metical
    NAD = 101, // Namibian Dollar
    NGN = 102, // Nigerian Naira
    NIO = 103, // Nicaraguan Córdoba
    NOK = 104, // Norwegian Krone
    NPR = 105, // Nepalese Rupee
    NZD = 106, // New Zealand Dollar
    OMR = 107, // Omani Rial
    PAB = 108, // Panamanian Balboa
    PEN = 109, // Peruvian Sol
    PGK = 110, // Papua New Guinean Kina
    PHP = 111, // Philippine Peso
    PKR = 112, // Pakistani Rupee
    PLN = 113, // Polish Złoty
    PYG = 114, // Paraguayan Guaraní
    QAR = 115, // Qatari Riyal
    RON = 116, // Romanian Leu
    RSD = 117, // Serbian Dinar
    RUB = 118, // Russian Ruble
    RWF = 119, // Rwandan Franc
    SAR = 120, // Saudi Riyal
    SBD = 121, // Solomon Islands Dollar
    SCR = 122, // Seychellois Rupee
    SDG = 123, // Sudanese Pound
    SEK = 124, // Swedish Krona
    SGD = 125, // Singapore Dollar
    SHP = 126, // Saint Helena Pound
    SLL = 127, // Sierra Leonean Leone
    SOS = 128, // Somali Shilling
    SRD = 129, // Surinamese Dollar
    SSP = 130, // South Sudanese Pound
    STN = 131, // São Tomé and Príncipe Dobra
    SYP = 132, // Syrian Pound
    SZL = 133, // Eswatini Lilangeni
    THB = 134, // Thai Baht
    TJS = 135, // Tajikistani Somoni
    TMT = 136, // Turkmenistani Manat
    TND = 137, // Tunisian Dinar
    TOP = 138, // Tongan Paʻanga
    TRY = 139, // Turkish Lira
    TTD = 140, // Trinidad and Tobago Dollar
    TVD = 141, // Tuvaluan Dollar
    TWD = 142, // New Taiwan Dollar
    TZS = 143, // Tanzanian Shilling
    UAH = 144, // Ukrainian Hryvnia
    UGX = 145, // Ugandan Shilling
    USD = 146, // United States Dollar
    UYU = 147, // Uruguayan Peso
    UZS = 148, // Uzbekistani Som
    VES = 149, // Venezuelan Bolívar
    VND = 150, // Vietnamese Đồng
    VUV = 151, // Vanuatu Vatu
    WST = 152, // Samoan Tālā
    XAF = 153, // Central African CFA Franc
    XCD = 154, // East Caribbean Dollar
    XOF = 155, // West African CFA Franc
    XPF = 156, // CFP Franc
    YER = 157, // Yemeni Rial
    ZAR = 158, // South African Rand
    ZMW = 159, // Zambian Kwacha
    ZWL = 160  // Zimbabwean Dollar
}
